<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\EquipmentBorrowing.Application\EquipmentBorrowing.Application.csproj" />
    <ProjectReference Include="..\..\src\EquipmentBorrowing.Domain\EquipmentBorrowing.Domain.csproj" />
    <ProjectReference Include="..\..\src\EquipmentBorrowing.Infrastructure\EquipmentBorrowing.Infrastructure.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
